export const TIER_LIMITS = {
  trial: {
    agents:               3,
    seats:                1,
    cron_jobs:            3,
    workflows:            0,
    context_files:        20,
    audit_retention_days: 30,
    requests_per_minute:  60,
    messages_per_day:     100,
  },
  starter: {
    agents:               10,
    seats:                3,
    cron_jobs:            10,
    workflows:            0,
    context_files:        100,
    audit_retention_days: 90,
    requests_per_minute:  120,
    messages_per_day:     1000,
  },
  professional: {
    agents:               50,
    seats:                10,
    cron_jobs:            50,
    workflows:            20,
    context_files:        500,
    audit_retention_days: 365,
    requests_per_minute:  300,
    messages_per_day:     5000,
  },
  enterprise: {
    agents:               Infinity,
    seats:                Infinity,
    cron_jobs:            Infinity,
    workflows:            Infinity,
    context_files:        Infinity,
    audit_retention_days: 1095,
    requests_per_minute:  Infinity,
    messages_per_day:     Infinity,
  },
}

export const FEATURES = {
  WORKFLOW_BUILDER:   'workflow_builder',
  AUDIT_EXPORT:       'audit_export',
  AUDIT_VIEW:         'audit_view',
  TEAM_MEMBERS:       'team_members',
  CRON_JOBS:          'cron_jobs',
  SSO:                'sso',
  CUSTOM_GUARD_RULES: 'custom_guard_rules',
  PROXY_MODE:         'proxy_mode',
  COMPLIANCE_REPORTS: 'compliance_reports',
  PBAC:               'pbac',
}

export const FEATURES_BY_PLAN = {
  trial: {
    audit_view: true,
    cron_jobs: true,
    audit_export: false,
    proxy_mode: false,
    compliance_reports: false,
    pbac: false,
    workflow_builder: false,
  },
  starter: {
    audit_view: true,
    cron_jobs: true,
    audit_export: false,
    proxy_mode: false,
    compliance_reports: false,
    pbac: false,
    workflow_builder: false,
  },
  professional: {
    audit_view: true,
    cron_jobs: true,
    audit_export: true,
    proxy_mode: true,
    compliance_reports: false,
    pbac: false,
    workflow_builder: true,
  },
  enterprise: {
    audit_view: true,
    cron_jobs: true,
    audit_export: true,
    proxy_mode: true,
    compliance_reports: true,
    pbac: true,
    workflow_builder: true,
    team_members: true,
    sso: true,
    custom_guard_rules: true,
  },
}
